--Structure

IF NOT EXISTS (SELECT *
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE='BASE TABLE'
	AND TABLE_NAME='User')
CREATE TABLE dbo.[User]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

IF NOT EXISTS (SELECT *
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE='BASE TABLE'
	AND TABLE_NAME='Game')
CREATE TABLE dbo.[Game]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdUser] [int] NOT NULL FOREIGN KEY REFERENCES dbo.[User](Id),
	[Time] [datetime] NOT NULL,
	CONSTRAINT [PK_Game] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

IF NOT EXISTS (SELECT *
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE='BASE TABLE'
	AND TABLE_NAME='Question')
CREATE TABLE dbo.[Question]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Latitude_verified] [varchar](13) NOT NULL,
	[Longitude_verified] [varchar](13) NOT NULL,
	[Name] [varchar](1000) NOT NULL,
	CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

IF NOT EXISTS (SELECT *
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE='BASE TABLE'
	AND TABLE_NAME='Question_Game')
CREATE TABLE dbo.[Question_Game]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdGame] [int] NOT NULL FOREIGN KEY REFERENCES dbo.[Game](Id),
	[IdQuestion] [int] NOT NULL FOREIGN KEY REFERENCES dbo.[Question](Id),
	[Latitude_answear] [varchar](13) NOT NULL,
	[Longitude_answear] [varchar](13) NOT NULL,
	[Score] [int] NOT NULL,
	CONSTRAINT [PK_Question_Game] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];